# ディスプレイ機能をオン！
CONFIG_ZMK_DISPLAY=y

# Bluetoothの安定性と接続数を確保
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# バッテリー表示とかをリッチにするなら
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
